// -*- c++ -*-

interface HelloWorld {
	long getTemp();
	long getPressure();
	long getWind();
        long getDistance();
        long getBigrock();
        long getDeepsand();
        long getmo();
};

